name: Check diff between latest commits and create an issue if the is a difference.

on:
  push:
    branches:
      - main
    paths:
      - templates/**

  workflow_dispatch:

jobs:

  check-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Find file changed
      id: find-changes
      run: |
        git fetch origin main
        echo file_changed=$(git diff --name-only HEAD^ HEAD | grep '^templates/') >> $GITHUB_OUTPUT

    - name: Find repos with file
      id: find_repos
      run: python template_config.py repos_per_file_check($file_changed)

    - name: Get diff between commits
      id: get-diff
      run: |
        git fetch origin main
        COMMIT1=$(git rev-parse HEAD)
        COMMIT2=$(git rev-parse HEAD^)
        DIFF=$(git diff $COMMIT2 $COMMIT1 -- templates/$file_changed templates/$file_changed)
        echo "diff<<EOF" >> $GITHUB_ENV
        echo "$DIFF" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  create_issues:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create GitHub Issues
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/HGWright/Templatee/issues
        owner: HGWright
        repo: Templatee
        title: "The Template for $file_changed has been updated"
        body: |
          |
          The template for `$file_changed` has been updated.
          
          Consider adopting these changes into the repo, the changes can be found below.
          
          The diff between the specified file is as follows.
          ```diff
          ${{ env.diff }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.Template_Token }}
