name: Check diff between latest commits and create an issue if the is a difference.

on:
  push:
    branches:
      - main
    paths:
      - templates/**

permissions:
  issues: write

jobs:

  check-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Get diff between commits
      id: get-diff
      run: |
        git fetch origin main
        COMMIT1=$(git rev-parse HEAD)
        COMMIT2=$(git rev-parse HEAD^)
        DIFF=$(git diff $COMMIT2 $COMMIT1 -- file_to_be_templated.yml file_to_be_templated.yml)
        echo "::set-output name=diff::$DIFF"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Issue
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/HGWright/Templatee/issues
        owner: HGWright
        repo: Templatee
        title: "The Template for file_to_be_templated.yml has been updated"
        body: |
          Does this work?
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
